### PR TITLE
feat: add accumulative accessible hook

### PR DESCRIPTION
**Pull request by pyphilia**

### CODE REVIEW

**Review by spaenleh — APPROVED** [review]
🚀 🧱

**Review by ReidyT — APPROVED** [review]
LGTM 👍 I'm not sure to understand the purpose of accumulating items through pagination 😅

**Comment by spaenleh** [comment]
@ReidyT The idea is to be able to grow the list instead of moving from a page to the other. Like you have on digitec when you click the load more button. This embraces a "infinite scroll" idea for displaying items.

**Comment by ReidyT** [comment]
@spaenleh Ah ok I see ! Thank you for your response 😆

**Pull request merged**
